// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2geY1gmM6AwADYjlNAXGdr0FvUwmmy3s',
    appId: '1:324487593002:web:e7e0765ce481251d1b9753',
    messagingSenderId: '324487593002',
    projectId: 'travelplan-511cd',
    authDomain: 'travelplan-511cd.firebaseapp.com',
    storageBucket: 'travelplan-511cd.appspot.com',
    measurementId: 'G-6GM13YZ3EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_VuxJyF14aJlB4gKjlMNKkQV0i9-DDY',
    appId: '1:324487593002:android:c6147076fa06db471b9753',
    messagingSenderId: '324487593002',
    projectId: 'travelplan-511cd',
    storageBucket: 'travelplan-511cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkAIY5DGVy1ebf83xLIC8-QodySJHVvrY',
    appId: '1:324487593002:ios:e947414b638ef86b1b9753',
    messagingSenderId: '324487593002',
    projectId: 'travelplan-511cd',
    storageBucket: 'travelplan-511cd.appspot.com',
    iosBundleId: 'com.example.travelplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkAIY5DGVy1ebf83xLIC8-QodySJHVvrY',
    appId: '1:324487593002:ios:1dc9a208124c8bce1b9753',
    messagingSenderId: '324487593002',
    projectId: 'travelplan-511cd',
    storageBucket: 'travelplan-511cd.appspot.com',
    iosBundleId: 'com.example.travelplan.RunnerTests',
  );
}
